# Generated by Django 4.1.2 on 2022-10-28 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_popular', models.CharField(max_length=255)),
                ('nome_cientifico', models.CharField(max_length=255)),
                ('sol_ou_sombra', models.CharField(choices=[('sp', 'Sol Pleno'), ('ms', 'Meia Sombra'), ('sb', 'Sombra')], max_length=2)),
                ('intervalo_rega', models.PositiveIntegerField()),
                ('ultima_rega', models.DateField()),
                ('foto_da_planta', models.ImageField(upload_to='')),
                ('descricao', models.TextField()),
            ],
        ),
    ]
