# Generated by Django 4.1.2 on 2022-10-30 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlantasApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planta',
            name='ultima_rega',
            field=models.DateField(blank=True, null=True),
        ),
    ]
