# Generated by Django 4.1.2 on 2022-11-03 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlantasApp', '0003_alter_planta_foto_da_planta'),
    ]

    operations = [
        migrations.AddField(
            model_name='planta',
            name='proxima_rega',
            field=models.DateField(blank=True, null=True),
        ),
    ]
